// Pulls ABIs out of `forge build` output (contracts/out/) into frontend/src/generated/abi/,
// so the frontend's contract typings always match what's actually deployed. Run this after any
// contract change: `npm run sync-abis` (requires `forge build` to have run in ../contracts first).
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outDir = join(__dirname, "..", "..", "contracts", "out");
const targetDir = join(__dirname, "..", "src", "generated", "abi");

const contracts = [
  "MandateRegistry",
  "PolicyEngine",
  "KillSwitch",
  "MockFXEscrow",
  "SettlementRouter",
  "MockERC20",
];

mkdirSync(targetDir, { recursive: true });

for (const name of contracts) {
  const artifactPath = join(outDir, `${name}.sol`, `${name}.json`);
  const artifact = JSON.parse(readFileSync(artifactPath, "utf-8"));
  // Written as a literal `as const` array (not a JSON import) so TypeScript keeps the literal
  // string types wagmi/viem need to infer function/event argument and return types.
  const contents = `// Auto-generated by scripts/sync-abis.mjs — do not edit by hand.\nexport const ${name}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  writeFileSync(join(targetDir, `${name}.ts`), contents);
  console.log(`synced ${name} (${artifact.abi.length} entries)`);
}
